services:
  official-website-2:
    container_name: official-website-2
    image: ghcr.io/octoberserver/official-website-2:latest
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.official-website-2.rule=Host(`octsrv.org`) || Host(`octoberserver.net`)"
      - "traefik.http.routers.official-website-2.entrypoints=web,websecure"
      - "traefik.http.routers.official-website-2.tls.certresolver=letsencrypt"
networks:
  web:
    external: true
